[package]
name = "project-kiwi"
version = "0.0.1-INDEV"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ffmpeg-sidecar = "1.1.0"


[workspace]
members = [
    "shared/proto",
    "shared/common",
    "shared/database",
    "shared/database/migration",
    "shared/web",
    # Services
    "services/relay",
    "services/snowflake",
    "services/gateway",
    "services/new_core",
    "services/media",
    "services/worker",
]
