[package]
name = "project-kiwi"
version = "0.0.1-INDEV"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html



[dev-dependencies]
criterion2 = { version = "0.9.0", features = ["tokio", "html_reports", "async_tokio"] }

[workspace]
members = [
    "shared/proto",
    "shared/common",
    "shared/database",
    "shared/database/migration",
    "shared/web",
    # Services
    "services/relay",
    "services/snowflake",
    "services/gateway",
    "services/core",
    "services/media",
    "services/worker",
    "services/frontend/src-tauri",
]
