[package]
name = "project-kiwi-c2"
version = "0.0.1-INDEV"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


[workspace]
members = [
    "audio",
    "snowflake",
    "shared/proto",
    "shared/common",
    "shared/database"
]
