version: "3.2"
services:
  frontend:
    build:
      dockerfile: frontend/Dockerfile
      context: .
    depends_on:
      - rethinkdb
      - postgres
    ports:
      - 3000:3000

  gateway:
    image: reg.phyrone.de/project-kiwi/gateway
    ports:
      - 7080:7080
    environment:
      GATEWAY_HTTP: "7080"

  snowflake:
    image: reg.phyrone.de/project-kiwi/snowflake
    build:
      dockerfile: services/snowflake/Dockerfile
      context: .
    environment:
      NODE_ID: "1"
    #command: "/usr/bin/snowflake"
    #command: sleep 1000000

  # Databases etc.
  meilisearch:
    image: getmeili/meilisearch
    environment:
      MEILI_ENV: development
  keydb:
    image: eqalpha/keydb
    command:
      - '--maxmemory 512mb'
      - '--maxmemory-policy allkeys-lfu'

  rethinkdb:
    image: rethinkdb
    environment:
      RETHINKDB_AUTH_KEY: "123456"

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: "kiwi"
      POSTGRES_PASSWORD: "kiwi"
      POSTGRES_DB: "kiwi"
    ports:
      - 5432:5432

  minio:
    image: quay.io/minio/minio
    volumes:
      - ./data/minio:/data
    entrypoint:
