openapi: 3.0.0
info:
  title: Gateway
  version: '2.0'
  description: Gateway API

paths:
  '/v1/health':
    get:
      summary: Health check
      operationId: healthCheck
      security:
        - bearerAuth: [ ]
      responses:
        200:
          description: Ok
          content:
            'text/xml':
              schema:
                $ref: '#/components/schemas/HealthStatusResponse'
            'text/yaml':
              schema:
                $ref: '#/components/schemas/HealthStatusResponse'
            'application/json':
              schema:
                $ref: '#/components/schemas/HealthStatusResponse'
        '500':
          description: Internal server error
          content:
            'application/problem+json':
              schema:
                type: object
                properties:
                  type:
                    type: string
                    default: 'https://httpstatuses.com/500'
                  title:
                    type: string
                    default: 'Internal Server Error'
                  status:
                    type: integer
                    default: 500
                  detail:
                    type: string
                    default: 'An internal server error occurred'
  '/v1/auth/login':
    post:
      description: Authenticate a user
      requestBody:
        required: true
        description: The user credentials
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/LoginRequest'
          'text/xml':
            schema:
              $ref: '#/components/schemas/LoginRequest'
          'text/yaml':
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        202:
          description: accepted
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/LoginSuccess'
            'text/xml':
              schema:
                $ref: '#/components/schemas/LoginSuccess'
            'text/yaml':
              schema:
                $ref: '#/components/schemas/LoginSuccess'




security:
  - bearerAuth: [ ]

components:
  schemas:
    HealthStatusResponse:
      type: object
      properties:
        healthy:
          type: boolean
          description: true if the service is healthy
          default: true
      xml:
        name: health-status
    LoginRequest:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
      required:
        - username
        - password
      xml:
        name: login-request
    LoginSuccess:
      type: object
      properties:
        token:
          type: string
      xml:
        name: login-success

    # RFC 9457 Error Response
    RFC9457Error:
      type: object
      properties:
        success:
          type: boolean
          default: false
        type:
          type: string
        title:
          type: string
        status:
          type: integer
        detail:
          type: string
        instance:
          type: string
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      name: Bearer Token

