// source: post.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() {
  if (this) { return this; }
  if (typeof window !== 'undefined') { return window; }
  if (typeof global !== 'undefined') { return global; }
  if (typeof self !== 'undefined') { return self; }
  return Function('return this')();
}.call(null));

var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
goog.object.extend(proto, google_protobuf_timestamp_pb);
goog.exportSymbol('proto.de.phyrone.kiwi.publications.Publication', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.de.phyrone.kiwi.publications.Publication = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.de.phyrone.kiwi.publications.Publication, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.de.phyrone.kiwi.publications.Publication.displayName = 'proto.de.phyrone.kiwi.publications.Publication';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.de.phyrone.kiwi.publications.Publication.prototype.toObject = function(opt_includeInstance) {
  return proto.de.phyrone.kiwi.publications.Publication.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.de.phyrone.kiwi.publications.Publication} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.de.phyrone.kiwi.publications.Publication.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0),
    isdraft: jspb.Message.getBooleanFieldWithDefault(msg, 2, false),
    title: jspb.Message.getFieldWithDefault(msg, 16, ""),
    content: jspb.Message.getFieldWithDefault(msg, 17, ""),
    userid: jspb.Message.getFieldWithDefault(msg, 49, 0),
    createdat: (f = msg.getCreatedat()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    updatedat: (f = msg.getUpdatedat()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    deletedat: (f = msg.getDeletedat()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.de.phyrone.kiwi.publications.Publication}
 */
proto.de.phyrone.kiwi.publications.Publication.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.de.phyrone.kiwi.publications.Publication;
  return proto.de.phyrone.kiwi.publications.Publication.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.de.phyrone.kiwi.publications.Publication} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.de.phyrone.kiwi.publications.Publication}
 */
proto.de.phyrone.kiwi.publications.Publication.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readSfixed64());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIsdraft(value);
      break;
    case 16:
      var value = /** @type {string} */ (reader.readString());
      msg.setTitle(value);
      break;
    case 17:
      var value = /** @type {string} */ (reader.readString());
      msg.setContent(value);
      break;
    case 49:
      var value = /** @type {number} */ (reader.readSfixed64());
      msg.setUserid(value);
      break;
    case 50:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setCreatedat(value);
      break;
    case 51:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setUpdatedat(value);
      break;
    case 52:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setDeletedat(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.de.phyrone.kiwi.publications.Publication.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.de.phyrone.kiwi.publications.Publication.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.de.phyrone.kiwi.publications.Publication} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.de.phyrone.kiwi.publications.Publication.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeSfixed64(
      1,
      f
    );
  }
  f = message.getIsdraft();
  if (f) {
    writer.writeBool(
      2,
      f
    );
  }
  f = message.getTitle();
  if (f.length > 0) {
    writer.writeString(
      16,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 17));
  if (f != null) {
    writer.writeString(
      17,
      f
    );
  }
  f = message.getUserid();
  if (f !== 0) {
    writer.writeSfixed64(
      49,
      f
    );
  }
  f = message.getCreatedat();
  if (f != null) {
    writer.writeMessage(
      50,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getUpdatedat();
  if (f != null) {
    writer.writeMessage(
      51,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getDeletedat();
  if (f != null) {
    writer.writeMessage(
      52,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
};


/**
 * optional sfixed64 id = 1;
 * @return {number}
 */
proto.de.phyrone.kiwi.publications.Publication.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.de.phyrone.kiwi.publications.Publication} returns this
 */
proto.de.phyrone.kiwi.publications.Publication.prototype.setId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional bool isDraft = 2;
 * @return {boolean}
 */
proto.de.phyrone.kiwi.publications.Publication.prototype.getIsdraft = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 2, false));
};


/**
 * @param {boolean} value
 * @return {!proto.de.phyrone.kiwi.publications.Publication} returns this
 */
proto.de.phyrone.kiwi.publications.Publication.prototype.setIsdraft = function(value) {
  return jspb.Message.setProto3BooleanField(this, 2, value);
};


/**
 * optional string title = 16;
 * @return {string}
 */
proto.de.phyrone.kiwi.publications.Publication.prototype.getTitle = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 16, ""));
};


/**
 * @param {string} value
 * @return {!proto.de.phyrone.kiwi.publications.Publication} returns this
 */
proto.de.phyrone.kiwi.publications.Publication.prototype.setTitle = function(value) {
  return jspb.Message.setProto3StringField(this, 16, value);
};


/**
 * optional string content = 17;
 * @return {string}
 */
proto.de.phyrone.kiwi.publications.Publication.prototype.getContent = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 17, ""));
};


/**
 * @param {string} value
 * @return {!proto.de.phyrone.kiwi.publications.Publication} returns this
 */
proto.de.phyrone.kiwi.publications.Publication.prototype.setContent = function(value) {
  return jspb.Message.setField(this, 17, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.de.phyrone.kiwi.publications.Publication} returns this
 */
proto.de.phyrone.kiwi.publications.Publication.prototype.clearContent = function() {
  return jspb.Message.setField(this, 17, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.de.phyrone.kiwi.publications.Publication.prototype.hasContent = function() {
  return jspb.Message.getField(this, 17) != null;
};


/**
 * optional sfixed64 userId = 49;
 * @return {number}
 */
proto.de.phyrone.kiwi.publications.Publication.prototype.getUserid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 49, 0));
};


/**
 * @param {number} value
 * @return {!proto.de.phyrone.kiwi.publications.Publication} returns this
 */
proto.de.phyrone.kiwi.publications.Publication.prototype.setUserid = function(value) {
  return jspb.Message.setProto3IntField(this, 49, value);
};


/**
 * optional google.protobuf.Timestamp createdAt = 50;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.de.phyrone.kiwi.publications.Publication.prototype.getCreatedat = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 50));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.de.phyrone.kiwi.publications.Publication} returns this
*/
proto.de.phyrone.kiwi.publications.Publication.prototype.setCreatedat = function(value) {
  return jspb.Message.setWrapperField(this, 50, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.de.phyrone.kiwi.publications.Publication} returns this
 */
proto.de.phyrone.kiwi.publications.Publication.prototype.clearCreatedat = function() {
  return this.setCreatedat(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.de.phyrone.kiwi.publications.Publication.prototype.hasCreatedat = function() {
  return jspb.Message.getField(this, 50) != null;
};


/**
 * optional google.protobuf.Timestamp updatedAt = 51;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.de.phyrone.kiwi.publications.Publication.prototype.getUpdatedat = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 51));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.de.phyrone.kiwi.publications.Publication} returns this
*/
proto.de.phyrone.kiwi.publications.Publication.prototype.setUpdatedat = function(value) {
  return jspb.Message.setWrapperField(this, 51, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.de.phyrone.kiwi.publications.Publication} returns this
 */
proto.de.phyrone.kiwi.publications.Publication.prototype.clearUpdatedat = function() {
  return this.setUpdatedat(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.de.phyrone.kiwi.publications.Publication.prototype.hasUpdatedat = function() {
  return jspb.Message.getField(this, 51) != null;
};


/**
 * optional google.protobuf.Timestamp deletedAt = 52;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.de.phyrone.kiwi.publications.Publication.prototype.getDeletedat = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 52));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.de.phyrone.kiwi.publications.Publication} returns this
*/
proto.de.phyrone.kiwi.publications.Publication.prototype.setDeletedat = function(value) {
  return jspb.Message.setWrapperField(this, 52, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.de.phyrone.kiwi.publications.Publication} returns this
 */
proto.de.phyrone.kiwi.publications.Publication.prototype.clearDeletedat = function() {
  return this.setDeletedat(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.de.phyrone.kiwi.publications.Publication.prototype.hasDeletedat = function() {
  return jspb.Message.getField(this, 52) != null;
};


goog.object.extend(exports, proto.de.phyrone.kiwi.publications);
