// source: snowflake.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() {
  if (this) { return this; }
  if (typeof window !== 'undefined') { return window; }
  if (typeof global !== 'undefined') { return global; }
  if (typeof self !== 'undefined') { return self; }
  return Function('return this')();
}.call(null));

var google_protobuf_empty_pb = require('google-protobuf/google/protobuf/empty_pb.js');
goog.object.extend(proto, google_protobuf_empty_pb);
goog.exportSymbol('proto.de.phyrone.kiwi.snowflake.Snowflake', null, global);
goog.exportSymbol('proto.de.phyrone.kiwi.snowflake.SnowflakesRequest', null, global);
goog.exportSymbol('proto.de.phyrone.kiwi.snowflake.SnowflakesResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.de.phyrone.kiwi.snowflake.SnowflakesRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.de.phyrone.kiwi.snowflake.SnowflakesRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.de.phyrone.kiwi.snowflake.SnowflakesRequest.displayName = 'proto.de.phyrone.kiwi.snowflake.SnowflakesRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.de.phyrone.kiwi.snowflake.SnowflakesResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.de.phyrone.kiwi.snowflake.SnowflakesResponse.repeatedFields_, null);
};
goog.inherits(proto.de.phyrone.kiwi.snowflake.SnowflakesResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.de.phyrone.kiwi.snowflake.SnowflakesResponse.displayName = 'proto.de.phyrone.kiwi.snowflake.SnowflakesResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.de.phyrone.kiwi.snowflake.Snowflake = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.de.phyrone.kiwi.snowflake.Snowflake, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.de.phyrone.kiwi.snowflake.Snowflake.displayName = 'proto.de.phyrone.kiwi.snowflake.Snowflake';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.de.phyrone.kiwi.snowflake.SnowflakesRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.de.phyrone.kiwi.snowflake.SnowflakesRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.de.phyrone.kiwi.snowflake.SnowflakesRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.de.phyrone.kiwi.snowflake.SnowflakesRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    count: jspb.Message.getFieldWithDefault(msg, 1, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.de.phyrone.kiwi.snowflake.SnowflakesRequest}
 */
proto.de.phyrone.kiwi.snowflake.SnowflakesRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.de.phyrone.kiwi.snowflake.SnowflakesRequest;
  return proto.de.phyrone.kiwi.snowflake.SnowflakesRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.de.phyrone.kiwi.snowflake.SnowflakesRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.de.phyrone.kiwi.snowflake.SnowflakesRequest}
 */
proto.de.phyrone.kiwi.snowflake.SnowflakesRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setCount(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.de.phyrone.kiwi.snowflake.SnowflakesRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.de.phyrone.kiwi.snowflake.SnowflakesRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.de.phyrone.kiwi.snowflake.SnowflakesRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.de.phyrone.kiwi.snowflake.SnowflakesRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCount();
  if (f !== 0) {
    writer.writeUint32(
      1,
      f
    );
  }
};


/**
 * optional uint32 count = 1;
 * @return {number}
 */
proto.de.phyrone.kiwi.snowflake.SnowflakesRequest.prototype.getCount = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.de.phyrone.kiwi.snowflake.SnowflakesRequest} returns this
 */
proto.de.phyrone.kiwi.snowflake.SnowflakesRequest.prototype.setCount = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.de.phyrone.kiwi.snowflake.SnowflakesResponse.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.de.phyrone.kiwi.snowflake.SnowflakesResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.de.phyrone.kiwi.snowflake.SnowflakesResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.de.phyrone.kiwi.snowflake.SnowflakesResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.de.phyrone.kiwi.snowflake.SnowflakesResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    snowflakesList: (f = jspb.Message.getRepeatedField(msg, 1)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.de.phyrone.kiwi.snowflake.SnowflakesResponse}
 */
proto.de.phyrone.kiwi.snowflake.SnowflakesResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.de.phyrone.kiwi.snowflake.SnowflakesResponse;
  return proto.de.phyrone.kiwi.snowflake.SnowflakesResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.de.phyrone.kiwi.snowflake.SnowflakesResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.de.phyrone.kiwi.snowflake.SnowflakesResponse}
 */
proto.de.phyrone.kiwi.snowflake.SnowflakesResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var values = /** @type {!Array<number>} */ (reader.isDelimited() ? reader.readPackedSfixed64() : [reader.readSfixed64()]);
      for (var i = 0; i < values.length; i++) {
        msg.addSnowflakes(values[i]);
      }
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.de.phyrone.kiwi.snowflake.SnowflakesResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.de.phyrone.kiwi.snowflake.SnowflakesResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.de.phyrone.kiwi.snowflake.SnowflakesResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.de.phyrone.kiwi.snowflake.SnowflakesResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSnowflakesList();
  if (f.length > 0) {
    writer.writePackedSfixed64(
      1,
      f
    );
  }
};


/**
 * repeated sfixed64 snowflakes = 1;
 * @return {!Array<number>}
 */
proto.de.phyrone.kiwi.snowflake.SnowflakesResponse.prototype.getSnowflakesList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 1));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.de.phyrone.kiwi.snowflake.SnowflakesResponse} returns this
 */
proto.de.phyrone.kiwi.snowflake.SnowflakesResponse.prototype.setSnowflakesList = function(value) {
  return jspb.Message.setField(this, 1, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.de.phyrone.kiwi.snowflake.SnowflakesResponse} returns this
 */
proto.de.phyrone.kiwi.snowflake.SnowflakesResponse.prototype.addSnowflakes = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 1, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.de.phyrone.kiwi.snowflake.SnowflakesResponse} returns this
 */
proto.de.phyrone.kiwi.snowflake.SnowflakesResponse.prototype.clearSnowflakesList = function() {
  return this.setSnowflakesList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.de.phyrone.kiwi.snowflake.Snowflake.prototype.toObject = function(opt_includeInstance) {
  return proto.de.phyrone.kiwi.snowflake.Snowflake.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.de.phyrone.kiwi.snowflake.Snowflake} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.de.phyrone.kiwi.snowflake.Snowflake.toObject = function(includeInstance, msg) {
  var f, obj = {
    snowflake: jspb.Message.getFieldWithDefault(msg, 1, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.de.phyrone.kiwi.snowflake.Snowflake}
 */
proto.de.phyrone.kiwi.snowflake.Snowflake.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.de.phyrone.kiwi.snowflake.Snowflake;
  return proto.de.phyrone.kiwi.snowflake.Snowflake.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.de.phyrone.kiwi.snowflake.Snowflake} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.de.phyrone.kiwi.snowflake.Snowflake}
 */
proto.de.phyrone.kiwi.snowflake.Snowflake.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readSfixed64());
      msg.setSnowflake(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.de.phyrone.kiwi.snowflake.Snowflake.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.de.phyrone.kiwi.snowflake.Snowflake.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.de.phyrone.kiwi.snowflake.Snowflake} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.de.phyrone.kiwi.snowflake.Snowflake.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSnowflake();
  if (f !== 0) {
    writer.writeSfixed64(
      1,
      f
    );
  }
};


/**
 * optional sfixed64 snowflake = 1;
 * @return {number}
 */
proto.de.phyrone.kiwi.snowflake.Snowflake.prototype.getSnowflake = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.de.phyrone.kiwi.snowflake.Snowflake} returns this
 */
proto.de.phyrone.kiwi.snowflake.Snowflake.prototype.setSnowflake = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


goog.object.extend(exports, proto.de.phyrone.kiwi.snowflake);
