[package]
name = "common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
error-stack = { version = "0.4.1", features = ["anyhow", "serde"] }
fast_log = { version = "1.6.16", features = ["zip"] }
log = { version = "0.4.21", features = ["serde", "std"] }


[lib]
path = "src/main/rust/lib.rs"
