// source: auth.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var proto = {};

goog.exportSymbol('de.phyrone.kiwi.auth.LoginRequest', null, proto);
goog.exportSymbol('de.phyrone.kiwi.auth.LoginRequest.LoginCase', null, proto);
goog.exportSymbol('de.phyrone.kiwi.auth.LoginRequest.UserPassword', null, proto);
goog.exportSymbol('de.phyrone.kiwi.auth.LoginRequest.WebAuthn', null, proto);
goog.exportSymbol('de.phyrone.kiwi.auth.ValidateSessionRequest', null, proto);
goog.exportSymbol('de.phyrone.kiwi.auth.ValidateSessionResponse', null, proto);
goog.exportSymbol('de.phyrone.kiwi.auth.ValidateSessionResponse.InvalidSession', null, proto);
goog.exportSymbol('de.phyrone.kiwi.auth.ValidateSessionResponse.ResponseCase', null, proto);
goog.exportSymbol('de.phyrone.kiwi.auth.ValidateSessionResponse.Session', null, proto);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.de.phyrone.kiwi.auth.ValidateSessionRequest = function (opt_data) {
	jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.de.phyrone.kiwi.auth.ValidateSessionRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
	/**
	 * @public
	 * @override
	 */
	proto.de.phyrone.kiwi.auth.ValidateSessionRequest.displayName =
		'proto.de.phyrone.kiwi.auth.ValidateSessionRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.de.phyrone.kiwi.auth.ValidateSessionResponse = function (opt_data) {
	jspb.Message.initialize(
		this,
		opt_data,
		0,
		-1,
		null,
		proto.de.phyrone.kiwi.auth.ValidateSessionResponse.oneofGroups_
	);
};
goog.inherits(proto.de.phyrone.kiwi.auth.ValidateSessionResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
	/**
	 * @public
	 * @override
	 */
	proto.de.phyrone.kiwi.auth.ValidateSessionResponse.displayName =
		'proto.de.phyrone.kiwi.auth.ValidateSessionResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.de.phyrone.kiwi.auth.ValidateSessionResponse.Session = function (opt_data) {
	jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.de.phyrone.kiwi.auth.ValidateSessionResponse.Session, jspb.Message);
if (goog.DEBUG && !COMPILED) {
	/**
	 * @public
	 * @override
	 */
	proto.de.phyrone.kiwi.auth.ValidateSessionResponse.Session.displayName =
		'proto.de.phyrone.kiwi.auth.ValidateSessionResponse.Session';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.de.phyrone.kiwi.auth.ValidateSessionResponse.InvalidSession = function (opt_data) {
	jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.de.phyrone.kiwi.auth.ValidateSessionResponse.InvalidSession, jspb.Message);
if (goog.DEBUG && !COMPILED) {
	/**
	 * @public
	 * @override
	 */
	proto.de.phyrone.kiwi.auth.ValidateSessionResponse.InvalidSession.displayName =
		'proto.de.phyrone.kiwi.auth.ValidateSessionResponse.InvalidSession';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.de.phyrone.kiwi.auth.LoginRequest = function (opt_data) {
	jspb.Message.initialize(
		this,
		opt_data,
		0,
		-1,
		null,
		proto.de.phyrone.kiwi.auth.LoginRequest.oneofGroups_
	);
};
goog.inherits(proto.de.phyrone.kiwi.auth.LoginRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
	/**
	 * @public
	 * @override
	 */
	proto.de.phyrone.kiwi.auth.LoginRequest.displayName = 'proto.de.phyrone.kiwi.auth.LoginRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.de.phyrone.kiwi.auth.LoginRequest.UserPassword = function (opt_data) {
	jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.de.phyrone.kiwi.auth.LoginRequest.UserPassword, jspb.Message);
if (goog.DEBUG && !COMPILED) {
	/**
	 * @public
	 * @override
	 */
	proto.de.phyrone.kiwi.auth.LoginRequest.UserPassword.displayName =
		'proto.de.phyrone.kiwi.auth.LoginRequest.UserPassword';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.de.phyrone.kiwi.auth.LoginRequest.WebAuthn = function (opt_data) {
	jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.de.phyrone.kiwi.auth.LoginRequest.WebAuthn, jspb.Message);
if (goog.DEBUG && !COMPILED) {
	/**
	 * @public
	 * @override
	 */
	proto.de.phyrone.kiwi.auth.LoginRequest.WebAuthn.displayName =
		'proto.de.phyrone.kiwi.auth.LoginRequest.WebAuthn';
}

if (jspb.Message.GENERATE_TO_OBJECT) {
	/**
	 * Creates an object representation of this proto.
	 * Field names that are reserved in JavaScript and will be renamed to pb_name.
	 * Optional fields that are not set will be set to undefined.
	 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
	 * For the list of reserved names please see:
	 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
	 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
	 *     JSPB instance for transitional soy proto support:
	 *     http://goto/soy-param-migration
	 * @return {!Object}
	 */
	proto.de.phyrone.kiwi.auth.ValidateSessionRequest.prototype.toObject = function (
		opt_includeInstance
	) {
		return proto.de.phyrone.kiwi.auth.ValidateSessionRequest.toObject(opt_includeInstance, this);
	};

	/**
	 * Static version of the {@see toObject} method.
	 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
	 *     the JSPB instance for transitional soy proto support:
	 *     http://goto/soy-param-migration
	 * @param {!proto.de.phyrone.kiwi.auth.ValidateSessionRequest} msg The msg instance to transform.
	 * @return {!Object}
	 * @suppress {unusedLocalVariables} f is only used for nested messages
	 */
	proto.de.phyrone.kiwi.auth.ValidateSessionRequest.toObject = function (includeInstance, msg) {
		var f,
			obj = {
				token: jspb.Message.getFieldWithDefault(msg, 1, '')
			};

		if (includeInstance) {
			obj.$jspbMessageInstance = msg;
		}
		return obj;
	};
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.de.phyrone.kiwi.auth.ValidateSessionRequest}
 */
proto.de.phyrone.kiwi.auth.ValidateSessionRequest.deserializeBinary = function (bytes) {
	var reader = new jspb.BinaryReader(bytes);
	var msg = new proto.de.phyrone.kiwi.auth.ValidateSessionRequest();
	return proto.de.phyrone.kiwi.auth.ValidateSessionRequest.deserializeBinaryFromReader(msg, reader);
};

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.de.phyrone.kiwi.auth.ValidateSessionRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.de.phyrone.kiwi.auth.ValidateSessionRequest}
 */
proto.de.phyrone.kiwi.auth.ValidateSessionRequest.deserializeBinaryFromReader = function (
	msg,
	reader
) {
	while (reader.nextField()) {
		if (reader.isEndGroup()) {
			break;
		}
		var field = reader.getFieldNumber();
		switch (field) {
			case 1:
				var value = /** @type {string} */ (reader.readString());
				msg.setToken(value);
				break;
			default:
				reader.skipField();
				break;
		}
	}
	return msg;
};

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.de.phyrone.kiwi.auth.ValidateSessionRequest.prototype.serializeBinary = function () {
	var writer = new jspb.BinaryWriter();
	proto.de.phyrone.kiwi.auth.ValidateSessionRequest.serializeBinaryToWriter(this, writer);
	return writer.getResultBuffer();
};

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.de.phyrone.kiwi.auth.ValidateSessionRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.de.phyrone.kiwi.auth.ValidateSessionRequest.serializeBinaryToWriter = function (
	message,
	writer
) {
	var f = undefined;
	f = message.getToken();
	if (f.length > 0) {
		writer.writeString(1, f);
	}
};

/**
 * optional string token = 1;
 * @return {string}
 */
proto.de.phyrone.kiwi.auth.ValidateSessionRequest.prototype.getToken = function () {
	return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ''));
};

/**
 * @param {string} value
 * @return {!proto.de.phyrone.kiwi.auth.ValidateSessionRequest} returns this
 */
proto.de.phyrone.kiwi.auth.ValidateSessionRequest.prototype.setToken = function (value) {
	return jspb.Message.setProto3StringField(this, 1, value);
};

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.de.phyrone.kiwi.auth.ValidateSessionResponse.oneofGroups_ = [[1, 2]];

/**
 * @enum {number}
 */
proto.de.phyrone.kiwi.auth.ValidateSessionResponse.ResponseCase = {
	RESPONSE_NOT_SET: 0,
	SESSION: 1,
	INVALIDSESSION: 2
};

/**
 * @return {proto.de.phyrone.kiwi.auth.ValidateSessionResponse.ResponseCase}
 */
proto.de.phyrone.kiwi.auth.ValidateSessionResponse.prototype.getResponseCase = function () {
	return /** @type {proto.de.phyrone.kiwi.auth.ValidateSessionResponse.ResponseCase} */ (
		jspb.Message.computeOneofCase(
			this,
			proto.de.phyrone.kiwi.auth.ValidateSessionResponse.oneofGroups_[0]
		)
	);
};

if (jspb.Message.GENERATE_TO_OBJECT) {
	/**
	 * Creates an object representation of this proto.
	 * Field names that are reserved in JavaScript and will be renamed to pb_name.
	 * Optional fields that are not set will be set to undefined.
	 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
	 * For the list of reserved names please see:
	 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
	 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
	 *     JSPB instance for transitional soy proto support:
	 *     http://goto/soy-param-migration
	 * @return {!Object}
	 */
	proto.de.phyrone.kiwi.auth.ValidateSessionResponse.prototype.toObject = function (
		opt_includeInstance
	) {
		return proto.de.phyrone.kiwi.auth.ValidateSessionResponse.toObject(opt_includeInstance, this);
	};

	/**
	 * Static version of the {@see toObject} method.
	 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
	 *     the JSPB instance for transitional soy proto support:
	 *     http://goto/soy-param-migration
	 * @param {!proto.de.phyrone.kiwi.auth.ValidateSessionResponse} msg The msg instance to transform.
	 * @return {!Object}
	 * @suppress {unusedLocalVariables} f is only used for nested messages
	 */
	proto.de.phyrone.kiwi.auth.ValidateSessionResponse.toObject = function (includeInstance, msg) {
		var f,
			obj = {
				session:
					(f = msg.getSession()) &&
					proto.de.phyrone.kiwi.auth.ValidateSessionResponse.Session.toObject(includeInstance, f),
				invalidsession:
					(f = msg.getInvalidsession()) &&
					proto.de.phyrone.kiwi.auth.ValidateSessionResponse.InvalidSession.toObject(
						includeInstance,
						f
					)
			};

		if (includeInstance) {
			obj.$jspbMessageInstance = msg;
		}
		return obj;
	};
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.de.phyrone.kiwi.auth.ValidateSessionResponse}
 */
proto.de.phyrone.kiwi.auth.ValidateSessionResponse.deserializeBinary = function (bytes) {
	var reader = new jspb.BinaryReader(bytes);
	var msg = new proto.de.phyrone.kiwi.auth.ValidateSessionResponse();
	return proto.de.phyrone.kiwi.auth.ValidateSessionResponse.deserializeBinaryFromReader(
		msg,
		reader
	);
};

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.de.phyrone.kiwi.auth.ValidateSessionResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.de.phyrone.kiwi.auth.ValidateSessionResponse}
 */
proto.de.phyrone.kiwi.auth.ValidateSessionResponse.deserializeBinaryFromReader = function (
	msg,
	reader
) {
	while (reader.nextField()) {
		if (reader.isEndGroup()) {
			break;
		}
		var field = reader.getFieldNumber();
		switch (field) {
			case 1:
				var value = new proto.de.phyrone.kiwi.auth.ValidateSessionResponse.Session();
				reader.readMessage(
					value,
					proto.de.phyrone.kiwi.auth.ValidateSessionResponse.Session.deserializeBinaryFromReader
				);
				msg.setSession(value);
				break;
			case 2:
				var value = new proto.de.phyrone.kiwi.auth.ValidateSessionResponse.InvalidSession();
				reader.readMessage(
					value,
					proto.de.phyrone.kiwi.auth.ValidateSessionResponse.InvalidSession
						.deserializeBinaryFromReader
				);
				msg.setInvalidsession(value);
				break;
			default:
				reader.skipField();
				break;
		}
	}
	return msg;
};

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.de.phyrone.kiwi.auth.ValidateSessionResponse.prototype.serializeBinary = function () {
	var writer = new jspb.BinaryWriter();
	proto.de.phyrone.kiwi.auth.ValidateSessionResponse.serializeBinaryToWriter(this, writer);
	return writer.getResultBuffer();
};

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.de.phyrone.kiwi.auth.ValidateSessionResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.de.phyrone.kiwi.auth.ValidateSessionResponse.serializeBinaryToWriter = function (
	message,
	writer
) {
	var f = undefined;
	f = message.getSession();
	if (f != null) {
		writer.writeMessage(
			1,
			f,
			proto.de.phyrone.kiwi.auth.ValidateSessionResponse.Session.serializeBinaryToWriter
		);
	}
	f = message.getInvalidsession();
	if (f != null) {
		writer.writeMessage(
			2,
			f,
			proto.de.phyrone.kiwi.auth.ValidateSessionResponse.InvalidSession.serializeBinaryToWriter
		);
	}
};

if (jspb.Message.GENERATE_TO_OBJECT) {
	/**
	 * Creates an object representation of this proto.
	 * Field names that are reserved in JavaScript and will be renamed to pb_name.
	 * Optional fields that are not set will be set to undefined.
	 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
	 * For the list of reserved names please see:
	 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
	 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
	 *     JSPB instance for transitional soy proto support:
	 *     http://goto/soy-param-migration
	 * @return {!Object}
	 */
	proto.de.phyrone.kiwi.auth.ValidateSessionResponse.Session.prototype.toObject = function (
		opt_includeInstance
	) {
		return proto.de.phyrone.kiwi.auth.ValidateSessionResponse.Session.toObject(
			opt_includeInstance,
			this
		);
	};

	/**
	 * Static version of the {@see toObject} method.
	 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
	 *     the JSPB instance for transitional soy proto support:
	 *     http://goto/soy-param-migration
	 * @param {!proto.de.phyrone.kiwi.auth.ValidateSessionResponse.Session} msg The msg instance to transform.
	 * @return {!Object}
	 * @suppress {unusedLocalVariables} f is only used for nested messages
	 */
	proto.de.phyrone.kiwi.auth.ValidateSessionResponse.Session.toObject = function (
		includeInstance,
		msg
	) {
		var f,
			obj = {};

		if (includeInstance) {
			obj.$jspbMessageInstance = msg;
		}
		return obj;
	};
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.de.phyrone.kiwi.auth.ValidateSessionResponse.Session}
 */
proto.de.phyrone.kiwi.auth.ValidateSessionResponse.Session.deserializeBinary = function (bytes) {
	var reader = new jspb.BinaryReader(bytes);
	var msg = new proto.de.phyrone.kiwi.auth.ValidateSessionResponse.Session();
	return proto.de.phyrone.kiwi.auth.ValidateSessionResponse.Session.deserializeBinaryFromReader(
		msg,
		reader
	);
};

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.de.phyrone.kiwi.auth.ValidateSessionResponse.Session} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.de.phyrone.kiwi.auth.ValidateSessionResponse.Session}
 */
proto.de.phyrone.kiwi.auth.ValidateSessionResponse.Session.deserializeBinaryFromReader = function (
	msg,
	reader
) {
	while (reader.nextField()) {
		if (reader.isEndGroup()) {
			break;
		}
		var field = reader.getFieldNumber();
		switch (field) {
			default:
				reader.skipField();
				break;
		}
	}
	return msg;
};

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.de.phyrone.kiwi.auth.ValidateSessionResponse.Session.prototype.serializeBinary = function () {
	var writer = new jspb.BinaryWriter();
	proto.de.phyrone.kiwi.auth.ValidateSessionResponse.Session.serializeBinaryToWriter(this, writer);
	return writer.getResultBuffer();
};

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.de.phyrone.kiwi.auth.ValidateSessionResponse.Session} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.de.phyrone.kiwi.auth.ValidateSessionResponse.Session.serializeBinaryToWriter = function (
	message,
	writer
) {
	var f = undefined;
};

if (jspb.Message.GENERATE_TO_OBJECT) {
	/**
	 * Creates an object representation of this proto.
	 * Field names that are reserved in JavaScript and will be renamed to pb_name.
	 * Optional fields that are not set will be set to undefined.
	 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
	 * For the list of reserved names please see:
	 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
	 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
	 *     JSPB instance for transitional soy proto support:
	 *     http://goto/soy-param-migration
	 * @return {!Object}
	 */
	proto.de.phyrone.kiwi.auth.ValidateSessionResponse.InvalidSession.prototype.toObject = function (
		opt_includeInstance
	) {
		return proto.de.phyrone.kiwi.auth.ValidateSessionResponse.InvalidSession.toObject(
			opt_includeInstance,
			this
		);
	};

	/**
	 * Static version of the {@see toObject} method.
	 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
	 *     the JSPB instance for transitional soy proto support:
	 *     http://goto/soy-param-migration
	 * @param {!proto.de.phyrone.kiwi.auth.ValidateSessionResponse.InvalidSession} msg The msg instance to transform.
	 * @return {!Object}
	 * @suppress {unusedLocalVariables} f is only used for nested messages
	 */
	proto.de.phyrone.kiwi.auth.ValidateSessionResponse.InvalidSession.toObject = function (
		includeInstance,
		msg
	) {
		var f,
			obj = {};

		if (includeInstance) {
			obj.$jspbMessageInstance = msg;
		}
		return obj;
	};
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.de.phyrone.kiwi.auth.ValidateSessionResponse.InvalidSession}
 */
proto.de.phyrone.kiwi.auth.ValidateSessionResponse.InvalidSession.deserializeBinary = function (
	bytes
) {
	var reader = new jspb.BinaryReader(bytes);
	var msg = new proto.de.phyrone.kiwi.auth.ValidateSessionResponse.InvalidSession();
	return proto.de.phyrone.kiwi.auth.ValidateSessionResponse.InvalidSession.deserializeBinaryFromReader(
		msg,
		reader
	);
};

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.de.phyrone.kiwi.auth.ValidateSessionResponse.InvalidSession} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.de.phyrone.kiwi.auth.ValidateSessionResponse.InvalidSession}
 */
proto.de.phyrone.kiwi.auth.ValidateSessionResponse.InvalidSession.deserializeBinaryFromReader =
	function (msg, reader) {
		while (reader.nextField()) {
			if (reader.isEndGroup()) {
				break;
			}
			var field = reader.getFieldNumber();
			switch (field) {
				default:
					reader.skipField();
					break;
			}
		}
		return msg;
	};

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.de.phyrone.kiwi.auth.ValidateSessionResponse.InvalidSession.prototype.serializeBinary =
	function () {
		var writer = new jspb.BinaryWriter();
		proto.de.phyrone.kiwi.auth.ValidateSessionResponse.InvalidSession.serializeBinaryToWriter(
			this,
			writer
		);
		return writer.getResultBuffer();
	};

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.de.phyrone.kiwi.auth.ValidateSessionResponse.InvalidSession} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.de.phyrone.kiwi.auth.ValidateSessionResponse.InvalidSession.serializeBinaryToWriter =
	function (message, writer) {
		var f = undefined;
	};

/**
 * optional Session session = 1;
 * @return {?proto.de.phyrone.kiwi.auth.ValidateSessionResponse.Session}
 */
proto.de.phyrone.kiwi.auth.ValidateSessionResponse.prototype.getSession = function () {
	return /** @type{?proto.de.phyrone.kiwi.auth.ValidateSessionResponse.Session} */ (
		jspb.Message.getWrapperField(
			this,
			proto.de.phyrone.kiwi.auth.ValidateSessionResponse.Session,
			1
		)
	);
};

/**
 * @param {?proto.de.phyrone.kiwi.auth.ValidateSessionResponse.Session|undefined} value
 * @return {!proto.de.phyrone.kiwi.auth.ValidateSessionResponse} returns this
 */
proto.de.phyrone.kiwi.auth.ValidateSessionResponse.prototype.setSession = function (value) {
	return jspb.Message.setOneofWrapperField(
		this,
		1,
		proto.de.phyrone.kiwi.auth.ValidateSessionResponse.oneofGroups_[0],
		value
	);
};

/**
 * Clears the message field making it undefined.
 * @return {!proto.de.phyrone.kiwi.auth.ValidateSessionResponse} returns this
 */
proto.de.phyrone.kiwi.auth.ValidateSessionResponse.prototype.clearSession = function () {
	return this.setSession(undefined);
};

/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.de.phyrone.kiwi.auth.ValidateSessionResponse.prototype.hasSession = function () {
	return jspb.Message.getField(this, 1) != null;
};

/**
 * optional InvalidSession invalidSession = 2;
 * @return {?proto.de.phyrone.kiwi.auth.ValidateSessionResponse.InvalidSession}
 */
proto.de.phyrone.kiwi.auth.ValidateSessionResponse.prototype.getInvalidsession = function () {
	return /** @type{?proto.de.phyrone.kiwi.auth.ValidateSessionResponse.InvalidSession} */ (
		jspb.Message.getWrapperField(
			this,
			proto.de.phyrone.kiwi.auth.ValidateSessionResponse.InvalidSession,
			2
		)
	);
};

/**
 * @param {?proto.de.phyrone.kiwi.auth.ValidateSessionResponse.InvalidSession|undefined} value
 * @return {!proto.de.phyrone.kiwi.auth.ValidateSessionResponse} returns this
 */
proto.de.phyrone.kiwi.auth.ValidateSessionResponse.prototype.setInvalidsession = function (value) {
	return jspb.Message.setOneofWrapperField(
		this,
		2,
		proto.de.phyrone.kiwi.auth.ValidateSessionResponse.oneofGroups_[0],
		value
	);
};

/**
 * Clears the message field making it undefined.
 * @return {!proto.de.phyrone.kiwi.auth.ValidateSessionResponse} returns this
 */
proto.de.phyrone.kiwi.auth.ValidateSessionResponse.prototype.clearInvalidsession = function () {
	return this.setInvalidsession(undefined);
};

/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.de.phyrone.kiwi.auth.ValidateSessionResponse.prototype.hasInvalidsession = function () {
	return jspb.Message.getField(this, 2) != null;
};

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.de.phyrone.kiwi.auth.LoginRequest.oneofGroups_ = [[1]];

/**
 * @enum {number}
 */
proto.de.phyrone.kiwi.auth.LoginRequest.LoginCase = {
	LOGIN_NOT_SET: 0,
	USERPASSWORD: 1
};

/**
 * @return {proto.de.phyrone.kiwi.auth.LoginRequest.LoginCase}
 */
proto.de.phyrone.kiwi.auth.LoginRequest.prototype.getLoginCase = function () {
	return /** @type {proto.de.phyrone.kiwi.auth.LoginRequest.LoginCase} */ (
		jspb.Message.computeOneofCase(this, proto.de.phyrone.kiwi.auth.LoginRequest.oneofGroups_[0])
	);
};

if (jspb.Message.GENERATE_TO_OBJECT) {
	/**
	 * Creates an object representation of this proto.
	 * Field names that are reserved in JavaScript and will be renamed to pb_name.
	 * Optional fields that are not set will be set to undefined.
	 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
	 * For the list of reserved names please see:
	 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
	 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
	 *     JSPB instance for transitional soy proto support:
	 *     http://goto/soy-param-migration
	 * @return {!Object}
	 */
	proto.de.phyrone.kiwi.auth.LoginRequest.prototype.toObject = function (opt_includeInstance) {
		return proto.de.phyrone.kiwi.auth.LoginRequest.toObject(opt_includeInstance, this);
	};

	/**
	 * Static version of the {@see toObject} method.
	 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
	 *     the JSPB instance for transitional soy proto support:
	 *     http://goto/soy-param-migration
	 * @param {!proto.de.phyrone.kiwi.auth.LoginRequest} msg The msg instance to transform.
	 * @return {!Object}
	 * @suppress {unusedLocalVariables} f is only used for nested messages
	 */
	proto.de.phyrone.kiwi.auth.LoginRequest.toObject = function (includeInstance, msg) {
		var f,
			obj = {
				userpassword:
					(f = msg.getUserpassword()) &&
					proto.de.phyrone.kiwi.auth.LoginRequest.UserPassword.toObject(includeInstance, f)
			};

		if (includeInstance) {
			obj.$jspbMessageInstance = msg;
		}
		return obj;
	};
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.de.phyrone.kiwi.auth.LoginRequest}
 */
proto.de.phyrone.kiwi.auth.LoginRequest.deserializeBinary = function (bytes) {
	var reader = new jspb.BinaryReader(bytes);
	var msg = new proto.de.phyrone.kiwi.auth.LoginRequest();
	return proto.de.phyrone.kiwi.auth.LoginRequest.deserializeBinaryFromReader(msg, reader);
};

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.de.phyrone.kiwi.auth.LoginRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.de.phyrone.kiwi.auth.LoginRequest}
 */
proto.de.phyrone.kiwi.auth.LoginRequest.deserializeBinaryFromReader = function (msg, reader) {
	while (reader.nextField()) {
		if (reader.isEndGroup()) {
			break;
		}
		var field = reader.getFieldNumber();
		switch (field) {
			case 1:
				var value = new proto.de.phyrone.kiwi.auth.LoginRequest.UserPassword();
				reader.readMessage(
					value,
					proto.de.phyrone.kiwi.auth.LoginRequest.UserPassword.deserializeBinaryFromReader
				);
				msg.setUserpassword(value);
				break;
			default:
				reader.skipField();
				break;
		}
	}
	return msg;
};

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.de.phyrone.kiwi.auth.LoginRequest.prototype.serializeBinary = function () {
	var writer = new jspb.BinaryWriter();
	proto.de.phyrone.kiwi.auth.LoginRequest.serializeBinaryToWriter(this, writer);
	return writer.getResultBuffer();
};

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.de.phyrone.kiwi.auth.LoginRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.de.phyrone.kiwi.auth.LoginRequest.serializeBinaryToWriter = function (message, writer) {
	var f = undefined;
	f = message.getUserpassword();
	if (f != null) {
		writer.writeMessage(
			1,
			f,
			proto.de.phyrone.kiwi.auth.LoginRequest.UserPassword.serializeBinaryToWriter
		);
	}
};

if (jspb.Message.GENERATE_TO_OBJECT) {
	/**
	 * Creates an object representation of this proto.
	 * Field names that are reserved in JavaScript and will be renamed to pb_name.
	 * Optional fields that are not set will be set to undefined.
	 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
	 * For the list of reserved names please see:
	 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
	 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
	 *     JSPB instance for transitional soy proto support:
	 *     http://goto/soy-param-migration
	 * @return {!Object}
	 */
	proto.de.phyrone.kiwi.auth.LoginRequest.UserPassword.prototype.toObject = function (
		opt_includeInstance
	) {
		return proto.de.phyrone.kiwi.auth.LoginRequest.UserPassword.toObject(opt_includeInstance, this);
	};

	/**
	 * Static version of the {@see toObject} method.
	 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
	 *     the JSPB instance for transitional soy proto support:
	 *     http://goto/soy-param-migration
	 * @param {!proto.de.phyrone.kiwi.auth.LoginRequest.UserPassword} msg The msg instance to transform.
	 * @return {!Object}
	 * @suppress {unusedLocalVariables} f is only used for nested messages
	 */
	proto.de.phyrone.kiwi.auth.LoginRequest.UserPassword.toObject = function (includeInstance, msg) {
		var f,
			obj = {
				username: jspb.Message.getFieldWithDefault(msg, 1, ''),
				password: jspb.Message.getFieldWithDefault(msg, 2, ''),
				otp: jspb.Message.getFieldWithDefault(msg, 3, '')
			};

		if (includeInstance) {
			obj.$jspbMessageInstance = msg;
		}
		return obj;
	};
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.de.phyrone.kiwi.auth.LoginRequest.UserPassword}
 */
proto.de.phyrone.kiwi.auth.LoginRequest.UserPassword.deserializeBinary = function (bytes) {
	var reader = new jspb.BinaryReader(bytes);
	var msg = new proto.de.phyrone.kiwi.auth.LoginRequest.UserPassword();
	return proto.de.phyrone.kiwi.auth.LoginRequest.UserPassword.deserializeBinaryFromReader(
		msg,
		reader
	);
};

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.de.phyrone.kiwi.auth.LoginRequest.UserPassword} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.de.phyrone.kiwi.auth.LoginRequest.UserPassword}
 */
proto.de.phyrone.kiwi.auth.LoginRequest.UserPassword.deserializeBinaryFromReader = function (
	msg,
	reader
) {
	while (reader.nextField()) {
		if (reader.isEndGroup()) {
			break;
		}
		var field = reader.getFieldNumber();
		switch (field) {
			case 1:
				var value = /** @type {string} */ (reader.readString());
				msg.setUsername(value);
				break;
			case 2:
				var value = /** @type {string} */ (reader.readString());
				msg.setPassword(value);
				break;
			case 3:
				var value = /** @type {string} */ (reader.readString());
				msg.setOtp(value);
				break;
			default:
				reader.skipField();
				break;
		}
	}
	return msg;
};

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.de.phyrone.kiwi.auth.LoginRequest.UserPassword.prototype.serializeBinary = function () {
	var writer = new jspb.BinaryWriter();
	proto.de.phyrone.kiwi.auth.LoginRequest.UserPassword.serializeBinaryToWriter(this, writer);
	return writer.getResultBuffer();
};

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.de.phyrone.kiwi.auth.LoginRequest.UserPassword} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.de.phyrone.kiwi.auth.LoginRequest.UserPassword.serializeBinaryToWriter = function (
	message,
	writer
) {
	var f = undefined;
	f = message.getUsername();
	if (f.length > 0) {
		writer.writeString(1, f);
	}
	f = message.getPassword();
	if (f.length > 0) {
		writer.writeString(2, f);
	}
	f = message.getOtp();
	if (f.length > 0) {
		writer.writeString(3, f);
	}
};

/**
 * optional string username = 1;
 * @return {string}
 */
proto.de.phyrone.kiwi.auth.LoginRequest.UserPassword.prototype.getUsername = function () {
	return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ''));
};

/**
 * @param {string} value
 * @return {!proto.de.phyrone.kiwi.auth.LoginRequest.UserPassword} returns this
 */
proto.de.phyrone.kiwi.auth.LoginRequest.UserPassword.prototype.setUsername = function (value) {
	return jspb.Message.setProto3StringField(this, 1, value);
};

/**
 * optional string password = 2;
 * @return {string}
 */
proto.de.phyrone.kiwi.auth.LoginRequest.UserPassword.prototype.getPassword = function () {
	return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ''));
};

/**
 * @param {string} value
 * @return {!proto.de.phyrone.kiwi.auth.LoginRequest.UserPassword} returns this
 */
proto.de.phyrone.kiwi.auth.LoginRequest.UserPassword.prototype.setPassword = function (value) {
	return jspb.Message.setProto3StringField(this, 2, value);
};

/**
 * optional string otp = 3;
 * @return {string}
 */
proto.de.phyrone.kiwi.auth.LoginRequest.UserPassword.prototype.getOtp = function () {
	return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ''));
};

/**
 * @param {string} value
 * @return {!proto.de.phyrone.kiwi.auth.LoginRequest.UserPassword} returns this
 */
proto.de.phyrone.kiwi.auth.LoginRequest.UserPassword.prototype.setOtp = function (value) {
	return jspb.Message.setProto3StringField(this, 3, value);
};

if (jspb.Message.GENERATE_TO_OBJECT) {
	/**
	 * Creates an object representation of this proto.
	 * Field names that are reserved in JavaScript and will be renamed to pb_name.
	 * Optional fields that are not set will be set to undefined.
	 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
	 * For the list of reserved names please see:
	 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
	 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
	 *     JSPB instance for transitional soy proto support:
	 *     http://goto/soy-param-migration
	 * @return {!Object}
	 */
	proto.de.phyrone.kiwi.auth.LoginRequest.WebAuthn.prototype.toObject = function (
		opt_includeInstance
	) {
		return proto.de.phyrone.kiwi.auth.LoginRequest.WebAuthn.toObject(opt_includeInstance, this);
	};

	/**
	 * Static version of the {@see toObject} method.
	 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
	 *     the JSPB instance for transitional soy proto support:
	 *     http://goto/soy-param-migration
	 * @param {!proto.de.phyrone.kiwi.auth.LoginRequest.WebAuthn} msg The msg instance to transform.
	 * @return {!Object}
	 * @suppress {unusedLocalVariables} f is only used for nested messages
	 */
	proto.de.phyrone.kiwi.auth.LoginRequest.WebAuthn.toObject = function (includeInstance, msg) {
		var f,
			obj = {
				username: jspb.Message.getFieldWithDefault(msg, 1, ''),
				challenge: jspb.Message.getFieldWithDefault(msg, 2, ''),
				origin: jspb.Message.getFieldWithDefault(msg, 3, '')
			};

		if (includeInstance) {
			obj.$jspbMessageInstance = msg;
		}
		return obj;
	};
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.de.phyrone.kiwi.auth.LoginRequest.WebAuthn}
 */
proto.de.phyrone.kiwi.auth.LoginRequest.WebAuthn.deserializeBinary = function (bytes) {
	var reader = new jspb.BinaryReader(bytes);
	var msg = new proto.de.phyrone.kiwi.auth.LoginRequest.WebAuthn();
	return proto.de.phyrone.kiwi.auth.LoginRequest.WebAuthn.deserializeBinaryFromReader(msg, reader);
};

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.de.phyrone.kiwi.auth.LoginRequest.WebAuthn} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.de.phyrone.kiwi.auth.LoginRequest.WebAuthn}
 */
proto.de.phyrone.kiwi.auth.LoginRequest.WebAuthn.deserializeBinaryFromReader = function (
	msg,
	reader
) {
	while (reader.nextField()) {
		if (reader.isEndGroup()) {
			break;
		}
		var field = reader.getFieldNumber();
		switch (field) {
			case 1:
				var value = /** @type {string} */ (reader.readString());
				msg.setUsername(value);
				break;
			case 2:
				var value = /** @type {string} */ (reader.readString());
				msg.setChallenge(value);
				break;
			case 3:
				var value = /** @type {string} */ (reader.readString());
				msg.setOrigin(value);
				break;
			default:
				reader.skipField();
				break;
		}
	}
	return msg;
};

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.de.phyrone.kiwi.auth.LoginRequest.WebAuthn.prototype.serializeBinary = function () {
	var writer = new jspb.BinaryWriter();
	proto.de.phyrone.kiwi.auth.LoginRequest.WebAuthn.serializeBinaryToWriter(this, writer);
	return writer.getResultBuffer();
};

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.de.phyrone.kiwi.auth.LoginRequest.WebAuthn} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.de.phyrone.kiwi.auth.LoginRequest.WebAuthn.serializeBinaryToWriter = function (
	message,
	writer
) {
	var f = undefined;
	f = message.getUsername();
	if (f.length > 0) {
		writer.writeString(1, f);
	}
	f = message.getChallenge();
	if (f.length > 0) {
		writer.writeString(2, f);
	}
	f = message.getOrigin();
	if (f.length > 0) {
		writer.writeString(3, f);
	}
};

/**
 * optional string username = 1;
 * @return {string}
 */
proto.de.phyrone.kiwi.auth.LoginRequest.WebAuthn.prototype.getUsername = function () {
	return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ''));
};

/**
 * @param {string} value
 * @return {!proto.de.phyrone.kiwi.auth.LoginRequest.WebAuthn} returns this
 */
proto.de.phyrone.kiwi.auth.LoginRequest.WebAuthn.prototype.setUsername = function (value) {
	return jspb.Message.setProto3StringField(this, 1, value);
};

/**
 * optional string challenge = 2;
 * @return {string}
 */
proto.de.phyrone.kiwi.auth.LoginRequest.WebAuthn.prototype.getChallenge = function () {
	return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ''));
};

/**
 * @param {string} value
 * @return {!proto.de.phyrone.kiwi.auth.LoginRequest.WebAuthn} returns this
 */
proto.de.phyrone.kiwi.auth.LoginRequest.WebAuthn.prototype.setChallenge = function (value) {
	return jspb.Message.setProto3StringField(this, 2, value);
};

/**
 * optional string origin = 3;
 * @return {string}
 */
proto.de.phyrone.kiwi.auth.LoginRequest.WebAuthn.prototype.getOrigin = function () {
	return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ''));
};

/**
 * @param {string} value
 * @return {!proto.de.phyrone.kiwi.auth.LoginRequest.WebAuthn} returns this
 */
proto.de.phyrone.kiwi.auth.LoginRequest.WebAuthn.prototype.setOrigin = function (value) {
	return jspb.Message.setProto3StringField(this, 3, value);
};

/**
 * optional UserPassword userPassword = 1;
 * @return {?proto.de.phyrone.kiwi.auth.LoginRequest.UserPassword}
 */
proto.de.phyrone.kiwi.auth.LoginRequest.prototype.getUserpassword = function () {
	return /** @type{?proto.de.phyrone.kiwi.auth.LoginRequest.UserPassword} */ (
		jspb.Message.getWrapperField(this, proto.de.phyrone.kiwi.auth.LoginRequest.UserPassword, 1)
	);
};

/**
 * @param {?proto.de.phyrone.kiwi.auth.LoginRequest.UserPassword|undefined} value
 * @return {!proto.de.phyrone.kiwi.auth.LoginRequest} returns this
 */
proto.de.phyrone.kiwi.auth.LoginRequest.prototype.setUserpassword = function (value) {
	return jspb.Message.setOneofWrapperField(
		this,
		1,
		proto.de.phyrone.kiwi.auth.LoginRequest.oneofGroups_[0],
		value
	);
};

/**
 * Clears the message field making it undefined.
 * @return {!proto.de.phyrone.kiwi.auth.LoginRequest} returns this
 */
proto.de.phyrone.kiwi.auth.LoginRequest.prototype.clearUserpassword = function () {
	return this.setUserpassword(undefined);
};

/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.de.phyrone.kiwi.auth.LoginRequest.prototype.hasUserpassword = function () {
	return jspb.Message.getField(this, 1) != null;
};

goog.object.extend(exports, proto);
