//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use super::sea_orm_active_enums::Flags;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "post"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize)]
pub struct Model {
    pub id: i64,
    pub channel_id: Option<i64>,
    pub author_id: Option<i64>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub title: String,
    pub body: Option<Json>,
    pub metadata: Option<Json>,
    pub tags: Option<Vec<String>>,
    pub flags: Option<Vec<Flags>>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    ChannelId,
    AuthorId,
    CreatedAt,
    UpdatedAt,
    Title,
    Body,
    Metadata,
    Tags,
    Flags,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = i64;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    Channel,
    PostAttachment,
    Profile,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::BigInteger.def(),
            Self::ChannelId => ColumnType::BigInteger.def().null(),
            Self::AuthorId => ColumnType::BigInteger.def().null(),
            Self::CreatedAt => ColumnType::TimestampWithTimeZone.def(),
            Self::UpdatedAt => ColumnType::TimestampWithTimeZone.def(),
            Self::Title => ColumnType::String(None).def(),
            Self::Body => ColumnType::JsonBinary.def().null(),
            Self::Metadata => ColumnType::JsonBinary.def().null(),
            Self::Tags => ColumnType::Array(RcOrArc::new(ColumnType::String(None)))
                .def()
                .null(),
            Self::Flags => ColumnType::Array(RcOrArc::new(Flags::db_type()))
                .def()
                .null(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::Channel => Entity::belongs_to(super::channel::Entity)
                .from(Column::ChannelId)
                .to(super::channel::Column::Id)
                .into(),
            Self::PostAttachment => Entity::has_many(super::post_attachment::Entity).into(),
            Self::Profile => Entity::belongs_to(super::profile::Entity)
                .from(Column::AuthorId)
                .to(super::profile::Column::Id)
                .into(),
        }
    }
}

impl Related<super::channel::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Channel.def()
    }
}

impl Related<super::post_attachment::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PostAttachment.def()
    }
}

impl Related<super::profile::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Profile.def()
    }
}

impl Related<super::asset::Entity> for Entity {
    fn to() -> RelationDef {
        super::post_attachment::Relation::Asset.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::post_attachment::Relation::Post.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
