//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "profile"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize)]
pub struct Model {
    pub id: i64,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub name: String,
    pub discriminator: Option<i16>,
    pub display_name: Option<String>,
    pub avatar: Option<i64>,
    pub banner: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    CreatedAt,
    UpdatedAt,
    Name,
    Discriminator,
    DisplayName,
    Avatar,
    Banner,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = i64;
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    Asset2,
    Asset1,
    Guild,
    Publication,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::BigInteger.def(),
            Self::CreatedAt => ColumnType::TimestampWithTimeZone.def(),
            Self::UpdatedAt => ColumnType::TimestampWithTimeZone.def(),
            Self::Name => ColumnType::String(StringLen::None).def(),
            Self::Discriminator => ColumnType::SmallInteger.def().null(),
            Self::DisplayName => ColumnType::String(StringLen::None).def().null(),
            Self::Avatar => ColumnType::BigInteger.def().null(),
            Self::Banner => ColumnType::BigInteger.def().null(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::Asset2 => Entity::belongs_to(super::asset::Entity)
                .from(Column::Avatar)
                .to(super::asset::Column::Id)
                .into(),
            Self::Asset1 => Entity::belongs_to(super::asset::Entity)
                .from(Column::Banner)
                .to(super::asset::Column::Id)
                .into(),
            Self::Guild => Entity::has_many(super::guild::Entity).into(),
            Self::Publication => Entity::has_many(super::publication::Entity).into(),
        }
    }
}

impl Related<super::guild::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Guild.def()
    }
}

impl Related<super::publication::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Publication.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
