//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "publication"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize)]
pub struct Model {
    pub id: i64,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub author_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    CreatedAt,
    UpdatedAt,
    AuthorId,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = i64;
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    Attachment,
    ChannelMessage,
    ContentFlag,
    Post,
    Profile,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::BigInteger.def(),
            Self::CreatedAt => ColumnType::TimestampWithTimeZone.def(),
            Self::UpdatedAt => ColumnType::TimestampWithTimeZone.def(),
            Self::AuthorId => ColumnType::BigInteger.def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::Attachment => Entity::has_many(super::attachment::Entity).into(),
            Self::ChannelMessage => Entity::has_one(super::channel_message::Entity).into(),
            Self::ContentFlag => Entity::has_many(super::content_flag::Entity).into(),
            Self::Post => Entity::has_one(super::post::Entity).into(),
            Self::Profile => Entity::belongs_to(super::profile::Entity)
                .from(Column::AuthorId)
                .to(super::profile::Column::Id)
                .into(),
        }
    }
}

impl Related<super::attachment::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Attachment.def()
    }
}

impl Related<super::channel_message::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChannelMessage.def()
    }
}

impl Related<super::content_flag::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ContentFlag.def()
    }
}

impl Related<super::post::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Post.def()
    }
}

impl Related<super::profile::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Profile.def()
    }
}

impl Related<super::asset::Entity> for Entity {
    fn to() -> RelationDef {
        super::attachment::Relation::Asset.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::attachment::Relation::Publication.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
