//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Copy, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "channel_type")]
pub enum ChannelType {
    #[sea_orm(string_value = "announcement")]
    Announcement,
    #[sea_orm(string_value = "dummy")]
    Dummy,
    #[sea_orm(string_value = "feed")]
    Feed,
    #[sea_orm(string_value = "forum")]
    Forum,
    #[sea_orm(string_value = "text")]
    Text,
    #[sea_orm(string_value = "voice")]
    Voice,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Copy, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "flags")]
pub enum Flags {
    #[sea_orm(string_value = "ai_generated")]
    AiGenerated,
    #[sea_orm(string_value = "automated")]
    Automated,
    #[sea_orm(string_value = "fake_news")]
    FakeNews,
    #[sea_orm(string_value = "nsfw")]
    Nsfw,
    #[sea_orm(string_value = "rageable")]
    Rageable,
    #[sea_orm(string_value = "spoilers")]
    Spoilers,
}
