DROP TABLE IF EXISTS post_attachment;
DROP TABLE IF EXISTS post_flag;
DROP TABLE IF EXISTS post_tag;
DROP TABLE IF EXISTS post;
DROP TABLE IF EXISTS profile;
DROP TABLE IF EXISTS asset_variant;
DROP TABLE IF EXISTS asset;
DROP TABLE IF EXISTS channel;
DROP TABLE IF EXISTS flyway_schema_history;
DROP TABLE IF EXISTS guild;
DROP TABLE IF EXISTS account_key;
DROP TABLE IF EXISTS account;

DROP TYPE IF EXISTS REMOTE;
DROP TYPE IF EXISTS PASSWORD;
DROP TYPE IF EXISTS CHANNEL_TYPE;
DROP TYPE IF EXISTS CONTENT_FLAG;