[package]
name = "sk-embedded"
version = "0.1.0"
edition = "2021"

[dependencies]
deno_console = "0.163.0"
deno_core = "0.300.0"
http = "1.1.0"
tokio = { version = "1.39.2", features = ["full", "tracing"] }
tokio-util = { version = "0.7.11", features = ["full", "tracing"] }
