//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Copy, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "content_flag")]
pub enum ContentFlag {
    #[sea_orm(string_value = "ai")]
    Ai,
    #[sea_orm(string_value = "automated")]
    Automated,
    #[sea_orm(string_value = "fake_news")]
    FakeNews,
    #[sea_orm(string_value = "nsfw")]
    Nsfw,
    #[sea_orm(string_value = "rageable")]
    Rageable,
    #[sea_orm(string_value = "spoilers")]
    Spoilers,
}
