DROP TABLE IF EXISTS "channel";
DROP TABLE IF EXISTS "guild";
DROP TABLE IF EXISTS "comment";

DROP TABLE IF EXISTS "post_attachment";
DROP TABLE IF EXISTS "post";


DROP TABLE IF EXISTS "profile";
DROP TABLE IF EXISTS "user_key";
DROP TABLE IF EXISTS "user";
DROP TABLE IF EXISTS "node";

DROP DOMAIN IF EXISTS email;
DROP EXTENSION IF EXISTS citext;