on:
  push:
    branches-ignore:
      - renovate/*
      - dependabot/*
name: Build Rust
jobs:
  prebuild_all:
    name: Prebuild All
    strategy:
      fail-fast: false
      matrix:
        target:
          - os: ubuntu-latest
            build_target: x86_64-unknown-linux-gnu
            install: |
                apt install protobuf-compiler
          - os: ubuntu-latest
            build_target: aarch64-unknown-linux-gnu
            install: |
              apt install protobuf-compiler
          - os: macos-latest
            build_target: x86_64-apple-darwin
            install: |
              brew install protobuf
          - os: macos-latest
            build_target: aarch64-apple-darwin
            install: |
              brew install protobuf

    runs-on: ${{ matrix.target.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Required Tools
        run: ${{ matrix.target.install }}
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target.build_target }}
      - name: Cache
        uses: Swatinem/rust-cache@v2
      - name: Build
        run: cargo build --target ${{ matrix.target.build_target }} --workspace
      - name: Build (Release)
        run: cargo build --target ${{ matrix.target.build_target }} --workspace --release
