on:
  push:
    branches-ignore:
      - renovate/*
      - dependabot/*
name: Build Rust
jobs:
  prebuild_all:
    name: Prebuild All
    strategy:
      fail-fast: false
      matrix:
        targets:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: windows-latest
            target: x86_64-pc-windows-msvc

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.targets.os }}
      - name: Cache
        uses: Swatinem/rust-cache@v2
      - name: Build
        run: cargo build --target ${{ matrix.targets.target }} --workspace
      - name: Build (Release)
        run: cargo build --target ${{ matrix.targets.target }} --workspace --release
