on:
  push:
    branches-ignore:
      - renovate/*
      - dependabot/*
name: Build Rust
jobs:
  prebuild_all:
    name: Prebuild All
    strategy:
      fail-fast: false
      matrix:
        target:
          - os: ubuntu-latest
            build_target: x86_64-unknown-linux-gnu
          - os: ubuntu-latest
            build_target: aarch64-unknown-linux-gnu
          - os: macos-latest
            build_target: x86_64-apple-darwin
          - os: macos-latest
            build_target: aarch64-apple-darwin

    runs-on: ${{ matrix.target.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Protoc
        uses: arduino/setup-protoc@v3
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target.build_target }}
      - name: Cache
        uses: Swatinem/rust-cache@v2
      - name: Build
        run: cargo build --target ${{ matrix.target.build_target }} --workspace
      - name: Build (Release)
        run: cargo build --target ${{ matrix.target.build_target }} --workspace --release
