on:
  push:
    paths:
      - 'page/**'
      - '.github/workflows/build-page.yaml'
      - 'package.json'
      - 'pnpm-lock.yaml'
#  pull_request:
#    paths:
#      - 'page/**'
#      - '.github/workflows/build-page.yaml'
#      - 'package.json'
#      - 'yarn.lock'
#      - 'bun.lockdb'
name: Page
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - name: Install dependencies
        uses: pnpm/action-setup@v3
        with:
          version: 'latest'
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-dependencies]
            - args: [--global, gulp, prettier, typescript]
      - name: Build
        working-directory: page
        run: pnpm run build --out-dir=dist
      - name: Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: page/dist
  deploy:
    needs:
      - build
    permissions:
      pages: write
      id-token: write
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    concurrency:
      cancel-in-progress: true
      group: "${{ github.workflow }}-${{ github.ref }}"
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        id: 'deployment'